version: '2'
services:
  db:
    image: postgres:14
    container_name: book.db
    hostname: localhost
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file:
      - .env
#    restart: always
